# -*- coding: utf-8 -*-
"""Solucion_IAA_DS_u2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1II1iCxpgNAUFLzqtl-B1DaxbECilqOuW

# **Enunciado**

En esta unidad hemos aprendido a realizar un Análisis Exploratorio de Datos con Python. En esta activad vamos a poner en práctica lo aprendido con un conjunto de datos real. Disponemos de un dataset con la información de admisiones a hospitales de enfermos de diabetes.

El objetivo final del proyecto es, estudiando el historial clínico de cada paciente, saber cuáles de ellos tienen una alta probabilidad de ser readmitidos en los próximos 30 días por problemas de diabetes. En el siguiente enlace puedes encontrar una descripción de todas las columnas:

https://fairlearn.org/main/user_guide/datasets/diabetes_hospital_data.html

La variable objetivo de nuestro estudio se llama readmit_30_days y es una variable binaria, 1 si el paciente fue readmitido en los siguientes 30 días y 0 en caso contrario.  

Ten en cuenta a la hora de estudiar las variables que las columnas readmitted y readmit_binary contienen esta misma información también pero no podríamos utilizarlas a la hora de predecir la otra porque realmente no se conocen hasta que un paciente es readmitido, que es el objetivo de nuestra predicción.

En modelos predictivos siempre hay que tener mucho cuidado con esto.

El esto de variables pueden ser consideradas variables independientes, algunas serán de tipo numérico y muchas de ellas de tipo categórico o binarias.

En esta actividad vamos a hacer un análisis exploratorio de datos tanto Univariante como Bivariante para entender mejor qué tratamientos tenemos que dar a cada variable y cuáles pueden ser relevantes a la hora de predecir si un paciente será readmitido en los próximos 30 días.

# **Análisis Univariante**

Identificación y Tratamiento de Nulos Cuenta cuantos valores nulos hay de cada variable, qué % representan y toma decisiones sobre cómo tratarlos.

Después de este paso no debería quedar ningún valor nulo.

# **Análisis de Variables Categóricas**

Ya que algunas veces se conviertes variables categóricas a numéricas vamos a empezar nuestro análisis por estas, incluyendo como categóricas las booleanas (True/False).

Haz un estudio de cada una de ellas de manera individualizada como vimos en la teoría.  

Como aún no vamos a trabajar con modelos de Machine Learning no es necesario la conversión a dummies final pero si ves alguna variable que únicamente toma dos valores conviértela a booleana, será más cómodo trabajar con ella más adelante.

Las preguntas que debemos ser capaces de responder son del tipo:

1. ¿hay columnas con valores constantes o casi constantes?
2. ¿Se debe reducir el número de categorías de alguna variable?
3. ¿tienen sentido los datos observados?

Además, aunque es una tareas más de tratamiento de datos, elimina todos los espacios de los valores de las categóricas que suelen dar problemas a veces y reemplázalos por '_'.

# **Análisis de Variables Numéricas**

Análisis Multivariante Estudia ahora cada una de las variables numéricas, observa las distribuciones y discute la presencia de outliers y la forma de tratarlos en cada caso.

Deberías como mínimo mostrar los boxplots y los histogramas de cada una de las variables para conocer su distribución.

Una vez completado el análisis univariante es hora de hacer el bivariante

1. ¿cómo se comportan las variables entre ellas? Nos importa especialmente la relación de cada variable con nuestro objetivo readmit_30_days.

# **Numérica vs Numérica**

Realiza primero un estudio de las correlaciones de todas las variables numéricas entre ellas

1. ¿hay alguna altamente correlada que podríamos descartar? Si es así muestra un scatter plot también de ellas para confirmar las sospechas.

# **Numérica vs Categórica**

En esta fase la idea principal es comparar cada una de las variables numéricas contra la variable objetivo, ¿tienen todas algo de relación con la probabilidad de un paciente ser readmitido a los 30 días? ¿podemos ya descartar alguna?

# **Categórica vs Categórica**

Al igual que con las numéricas, observa el comportamiento de cada una de estas variables categóricas con respecto a la variable objetivo. Emplea los test de chicuadrado

# **Código**

**Instalamos las librerias necesarias**
"""

# Instalar librerías necesarias
!pip install fairlearn pandas numpy matplotlib seaborn scipy

# Importar librerías
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from fairlearn.datasets import fetch_diabetes_hospital
from scipy.stats import chi2_contingency

# Configuración de visualización
plt.style.use('ggplot')
pd.set_option('display.max_columns', None)

# Cargar el dataset desde Fairlearn
dataset = fetch_diabetes_hospital(as_frame=True)
data = dataset['data']  # Asegurar que 'data' está correctamente asignado

# Mostrar las primeras filas para confirmar que los datos se cargaron correctamente
print("Vista previa de los datos:")
display(data.head())

# Mostrar información general del dataset
print("\nInformación del dataset:")
data.info()

# Verificar valores nulos
print("\nValores nulos por columna:")
print(data.isnull().sum())

"""# **Manejo de Valores Nulos**"""

# Identificar valores nulos
missing_values = data.isnull().sum()
missing_percentage = (missing_values / len(data)) * 100
missing_df = pd.DataFrame({'Valores Nulos': missing_values, 'Porcentaje': missing_percentage})
missing_df = missing_df[missing_df['Valores Nulos'] > 0].sort_values(by='Porcentaje', ascending=False)

# Si hay valores nulos, los mostramos
if not missing_df.empty:
    print("\nVariables con valores nulos:")
    display(missing_df)

    # Tratamiento de valores nulos
    for col in data.columns:
        if data[col].dtype == 'object' or data[col].dtype.name == 'category':
            # Reemplazar valores nulos en columnas categóricas con "Desconocido"
            data[col] = data[col].fillna('Desconocido')
        elif np.issubdtype(data[col].dtype, np.number):
            # Reemplazar valores nulos en columnas numéricas con la mediana
            data[col] = data[col].fillna(data[col].median())

    # Verificar que no haya nulos después del tratamiento
    print("\nValores nulos después del tratamiento:", data.isnull().sum().sum())  # Debe ser 0
else:
    print("\n✅ No hay valores nulos en el dataset.")

"""# **Análisis Univariante**

**A) Variables Categóricas**
"""

# Reemplazar espacios en valores categóricos para evitar problemas en modelos
for col in data.select_dtypes(include=['object']).columns:
    data.loc[:, col] = data[col].str.replace(' ', '_')

# Resumen de variables categóricas
print("\n🔍 Resumen de variables categóricas:")
for col in data.select_dtypes(include=['object']).columns:
    print(f"📌 {col}: {data[col].nunique()} categorías")
    print(data[col].value_counts(normalize=True) * 100)
    print("\n")

# Convertir variables binarias a 0 y 1 para facilitar análisis
binary_cols = ['diabetesMed', 'medicare', 'medicaid', 'had_emergency', 'had_inpatient_days', 'had_outpatient_days', 'readmit_binary']

for col in binary_cols:
    if data[col].dtype == 'object':  # Asegurar que es tipo 'object' antes de reemplazar
        data.loc[:, col] = data[col].replace({'No': 0, 'Yes': 1}).astype(int)

# Verificar que las variables binarias fueron correctamente convertidas
print("\n✅ Verificación de variables binarias:")
print(data[binary_cols].head())

"""**B) Variables Numéricas**"""

# Estadísticas de variables numéricas
print("\nResumen de variables numéricas:")
display(data.describe())

# Boxplot para detectar outliers
plt.figure(figsize=(12, 6))
sns.boxplot(data=data.select_dtypes(include=[np.number]))
plt.title("Boxplot de Variables Numéricas")
plt.xticks(rotation=45)
plt.show()

# Histogramas de variables numéricas
data.select_dtypes(include=[np.number]).hist(figsize=(12, 10), bins=30, edgecolor='black')
plt.suptitle("Histogramas de Variables Numéricas", fontsize=16)
plt.show()

"""# **Análisis Bivariante**

**A) Correlación entre Variables Numéricas**
"""

import seaborn as sns
import matplotlib.pyplot as plt

# Seleccionamos solo las columnas numéricas para evitar errores en la correlación
numeric_data = data.select_dtypes(include=['int64', 'float64'])

# Matriz de correlación corregida
plt.figure(figsize=(12, 6))
sns.heatmap(numeric_data.corr(), annot=True, fmt=".2f", cmap='coolwarm', linewidths=0.5)
plt.title("Matriz de Correlación entre Variables Numéricas")
plt.show()

# Identificar pares de variables altamente correlacionadas (correlación > 0.7)
correlated_features = set()
correlation_matrix = numeric_data.corr()

for i in range(len(correlation_matrix.columns)):
    for j in range(i):
        if abs(correlation_matrix.iloc[i, j]) > 0.7:
            colname = correlation_matrix.columns[i]
            correlated_features.add(colname)

print("\nVariables altamente correlacionadas que podríamos descartar:")
print(correlated_features)

"""No hay variables con correlación > 0.7, por lo que no es necesario eliminar ninguna por multicolinealidad.
Sin embargo, si buscamos reducir la dimensionalidad, podríamos explorar métodos como PCA (Análisis de Componentes Principales) o realizar pruebas con modelos para ver qué variables realmente aportan al rendimiento.

**B) Relación entre Variables Numéricas y readmit_30_days**
"""

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Identificamos columnas numéricas excluyendo las binarias (0 y 1)
numeric_cols = [col for col in data.select_dtypes(include=[np.number]).columns if data[col].nunique() > 2]

# Boxplot de variables numéricas contra la variable objetivo
for col in numeric_cols:
    plt.figure(figsize=(8, 4))
    sns.boxplot(x=data['readmit_binary'].astype(str), y=data[col])
    plt.title(f"Distribución de {col} por Readmisión")
    plt.xlabel("Readmitido en 30 días (0 = No, 1 = Sí)")
    plt.ylabel(col)
    plt.show()

"""**C) Relación entre Variables Categóricas y readmit_30_days**"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import chi2_contingency

# Test de chi-cuadrado para variables categóricas
print("\n Test de Chi-Cuadrado entre variables categóricas y la readmisión:")
categorical_cols = data.select_dtypes(include=['object', 'category']).columns

for col in categorical_cols:
    contingency_table = pd.crosstab(data[col], data['readmit_binary'], dropna=False)
    chi2, p, dof, expected = chi2_contingency(contingency_table)

    print(f"\n🔹 {col} - p-valor: {p:.5f}")
    if p < 0.05:
        print("✅ → Relación significativa con la readmisión")
    else:
        print("❌ → No hay relación significativa con la readmisión")

# Gráfico de barras de frecuencia de variables categóricas por readmisión
for col in categorical_cols:
    plt.figure(figsize=(10, 5))
    sns.countplot(data=data, x=col, hue=data['readmit_binary'].astype(str))
    plt.title(f"Distribución de {col} por Readmisión")
    plt.xlabel(col)
    plt.ylabel("Frecuencia")
    plt.legend(title="Readmitido", labels=["No", "Sí"])
    plt.xticks(rotation=45)
    plt.show()

"""Casi todas las variables categóricas tienen un impacto significativo en la readmisión, lo que indica que el historial clínico y el tratamiento del paciente pueden jugar un papel clave.

La variable medicaid no tiene un impacto estadístico significativo, por lo que podríamos descartarla en el modelo final.

# **Revisión del Enunciado y respuesta en nuestro análisis**

1️⃣ <font color="red">Manejo de Valores Nulos</font> ✅ <font color="green">RESUELTO</font>

1. Identificamos valores nulos: No hay valores nulos en el dataset.

2. Método de imputación: No fue necesario realizar imputaciones porque no hay valores nulos.

2️⃣ <font color="red">Análisis Univariante</font>

A) Variables Categóricas ✅ <font color="green">RESUELTO</font>

Estudiamos cada variable categórica y mostramos su distribución.

Convertimos las binarias a booleanas (diabetesMed, medicare, medicaid, had_emergency, had_inpatient_days, had_outpatient_days, readmit_binary).

Limpieza de valores: Se reemplazaron los espacios en los valores categóricos con _ para evitar problemas de procesamiento.

<font color="red">Respondimos las preguntas clave?:</font>

***¿Hay valores constantes o casi constantes?***

medicaid tiene una distribución muy desigual y además no tiene una relación significativa con la readmisión.

*¿Se debe reducir el número de categorías de alguna variable?*

Variables como medical_specialty y primary_diagnosis podrían agruparse más en futuras etapas.

***¿Tienen sentido los datos observados?***

Sí, los valores y distribuciones parecen lógicos y consistentes con el problema.

B) Variables Numéricas ✅ <font color="green">RESUELTO</font>

**Análisis de distribución:**

Mostramos los boxplots e histogramas para observar la dispersión y outliers.

**Resumen estadístico:**

Se analizaron media, mediana, percentiles y valores máximos/mínimos.

**Detección de outliers:**

Algunos valores extremos, pero no eliminamos nada sin un criterio específico.

3️⃣ <font color="red">Análisis Bivariante</font>

A) Correlación entre Variables Numéricas ✅ <font color="green">RESUELTO</font>

Calculamos la matriz de correlación y la representamos con un heatmap.

<font color="red">Hallazgos:</font> No hay variables con correlación >0.7, por lo que no eliminamos ninguna por multicolinealidad.

<font color="red">Sugerencia:</font> En futuras etapas, podríamos aplicar PCA o feature selection para reducir la dimensionalidad.

B) Relación entre Variables Numéricas y readmit_30_days ✅ <font color="green">RESUELTO</font>

Se analizaron boxplots de cada variable numérica contra la readmisión.

C) Relación entre Variables Categóricas y readmit_30_days ✅ <font color="green">RESUELTO</font>

Realizamos el test de Chi-Cuadrado para todas las variables categóricas.

**Insights:**

Casi todas las variables categóricas tienen una relación significativa con la readmisión.
medicaid fue la única sin relación significativa, por lo que podemos eliminarla en la fase de modelado.
"""