# -*- coding: utf-8 -*-
"""Solucion_IEP_IAA_TS_Caso_practico_u1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BoFjmEJJ3q8NwW5bCAcmdBGdIywsBy-z

Empezamos importando las librerias necesarias
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.seasonal import seasonal_decompose

"""Cargamos el dataset referido en el enunciado, descargado en mi ambiente Google drive"""

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/datos_IEP_IAA_TS_u1/AirPassengers.csv')
df.columns = ['Month', 'Passengers']  # Asegura nombres consistentes
df['Month'] = pd.to_datetime(df['Month'])
df.set_index('Month', inplace=True)

"""Realizamos una visualización básica de la serie temporal"""

plt.figure(figsize=(12, 5))
plt.plot(df.index, df['Passengers'], label='Pasajeros')
plt.title('Serie temporal - AirPassengers')
plt.xlabel('Fecha')
plt.ylabel('Número de pasajeros')
plt.grid(True)
plt.legend()
plt.show()

"""Ahora, una visualizacion por año y por mes"""

df['Year'] = df.index.year
df['Month_num'] = df.index.month
df['Month'] = df.index.strftime('%b')

plt.figure(figsize=(12, 6))
sns.boxplot(x='Month', y='Passengers', data=df, order=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])
plt.title('Distribución mensual de pasajeros')
plt.show()

"""Hacemos una descomposición de la serie temporal"""

result = seasonal_decompose(df['Passengers'], model='multiplicative')
result.plot()
plt.suptitle('Descomposición de la serie temporal', fontsize=16)
plt.tight_layout()
plt.show()

"""Correlación temporal (opcional)"""

from pandas.plotting import autocorrelation_plot
autocorrelation_plot(df['Passengers'])
plt.title('Autocorrelación')
plt.show()

"""La exploración visual del dataset AirPassengers nos ha permitido identificar patrones clave en la serie temporal, como una tendencia creciente a lo largo de los años y una estacionalidad marcada con picos de demanda recurrentes en determinados meses del año. La descomposición de la serie confirmó estos componentes (tendencia, estacionalidad y ruido), fundamentales para aplicar modelos de predicción como ARIMA. Estas visualizaciones son esenciales para diagnosticar el comportamiento de la serie y definir el preprocesamiento necesario antes del modelado.

**Otras variantes que podríamos haber usado:**

1. Transformaciones logarítmicas o de Box-Cox:

  Para estabilizar la varianza si se observa heterocedasticidad (variación creciente con el tiempo).

2. Gráficos de calor (heatmaps) de estacionalidad:

  Para visualizar fácilmente las variaciones mensuales por año.

3. Diagramas de autocorrelación parcial (PACF):

  Útiles para identificar el orden AR en un modelo ARIMA.

4. Rolling mean y rolling std:

  Para verificar visualmente si la serie es estacionaria.

5. Análisis con statsmodels o pmdarima:

  Para pruebas estadísticas como el test de Dickey-Fuller (ADF).

Cambio de dataset:

Podríamos haber usado otro dataset multivariado (como ventas de productos con varias variables) para ver cómo interactúan diferentes factores.
"""